title: pentester.
description: "A place for some things..."
author:
  name: "synick"
  email: "blog@pentester.com.au"
  url: "https://blog.pentester.com.au"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/
remote_theme: fongandrew/hydeout

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "synick"
year : "2019"
